### ISSUE TITLE
Brewmaster loadscreen comes up as a white box in pick phase

### ISSUE THREAD

**Issue by NoFallDamage** [Crazy-Duck/junglenational#4]
Brewmaster loadscreen is missing and instead comes up as a white box in pick phase. (Hero still pickable)

**Comment by Crazy-Duck** [comment]
probably messed up the reference to the loadingscreen in the vpk, gonna have to check with gcfscape

**Comment by Crazy-Duck** [comment]
Fixed locally, just need to push to github
