### ISSUE TITLE
Picking Lina gives you Dragon Knight instead

### ISSUE THREAD

**Issue by NoFallDamage** [Crazy-Duck/junglenational#6]
Selecting Lina will instead give you Dragon Knight.

**Comment by Crazy-Duck** [comment]
change junglenational/panorama/scripts/custom_game/hero_selection.js and update dragon knight entry with dragon knight loading screen instead of lina loading screen
proposition: https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/6a/Cosmetic_icon_Knight_of_the_Burning_Scale_Loading_Screen.png

**Comment by Crazy-Duck** [comment]
Fixed locally, just need to push to github
